using UnityEngine;

public class AutoCreateScriptableObjectAttribute : PropertyAttribute
{
    public readonly string assetPath;

    public AutoCreateScriptableObjectAttribute(string assetPath = "Assets/ScriptableObject/AutoGenerated")
    {
        this.assetPath = assetPath;
    }
}
